//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDFCERGO.PIP.Adapters.OtherDetails
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClsInOut", Namespace="http://schemas.datacontract.org/2004/07/OtherDetailsService")]
    public partial class ClsInOut : object
    {
        
        private string AutoRenewalField;
        
        private string BDRCODEField;
        
        private string BankBranchIdField;
        
        private string BankLocationField;
        
        private string CUSTOMERIDField;
        
        private string ChannelNumberField;
        
        private string Decoration_SIField;
        
        private string EMIOptionField;
        
        private string EMIValueField;
        
        private string Electrical_Appliances_SIField;
        
        private string Electronic_Appliances_SIField;
        
        private string ErgoChannelIDField;
        
        private string Error_MsgField;
        
        private string Excess_Deductible_SIField;
        
        private string FOSCODEField;
        
        private string Footware_SIField;
        
        private string Furniture_SIField;
        
        private string HealthCoupnField;
        
        private string Kitchen_Appliances_SIField;
        
        private string LCCODEField;
        
        private string LGCODEField;
        
        private string LMSIDField;
        
        private string LOSCODEField;
        
        private string Nominee_NameField;
        
        private string Nominee_RelationField;
        
        private string Other_Annexure_SIField;
        
        private string PolicyNumberField;
        
        private string Proposer_CountryField;
        
        private string Proposer_QualificationField;
        
        private string RelationshipTypeField;
        
        private string SAVINGACCNOField;
        
        private string SMCODEField;
        
        private string TPANameField;
        
        private string TP_POLICY_ENDDTField;
        
        private string TP_POLICY_INCField;
        
        private string TP_POLICY_NUMBERField;
        
        private string TP_POLICY_STARTDTField;
        
        private string VerifiedIDField;
        
        private string Visa_Expiry_DtField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AutoRenewal
        {
            get
            {
                return this.AutoRenewalField;
            }
            set
            {
                this.AutoRenewalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BDRCODE
        {
            get
            {
                return this.BDRCODEField;
            }
            set
            {
                this.BDRCODEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankBranchId
        {
            get
            {
                return this.BankBranchIdField;
            }
            set
            {
                this.BankBranchIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankLocation
        {
            get
            {
                return this.BankLocationField;
            }
            set
            {
                this.BankLocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CUSTOMERID
        {
            get
            {
                return this.CUSTOMERIDField;
            }
            set
            {
                this.CUSTOMERIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChannelNumber
        {
            get
            {
                return this.ChannelNumberField;
            }
            set
            {
                this.ChannelNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Decoration_SI
        {
            get
            {
                return this.Decoration_SIField;
            }
            set
            {
                this.Decoration_SIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMIOption
        {
            get
            {
                return this.EMIOptionField;
            }
            set
            {
                this.EMIOptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMIValue
        {
            get
            {
                return this.EMIValueField;
            }
            set
            {
                this.EMIValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Electrical_Appliances_SI
        {
            get
            {
                return this.Electrical_Appliances_SIField;
            }
            set
            {
                this.Electrical_Appliances_SIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Electronic_Appliances_SI
        {
            get
            {
                return this.Electronic_Appliances_SIField;
            }
            set
            {
                this.Electronic_Appliances_SIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErgoChannelID
        {
            get
            {
                return this.ErgoChannelIDField;
            }
            set
            {
                this.ErgoChannelIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error_Msg
        {
            get
            {
                return this.Error_MsgField;
            }
            set
            {
                this.Error_MsgField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Excess_Deductible_SI
        {
            get
            {
                return this.Excess_Deductible_SIField;
            }
            set
            {
                this.Excess_Deductible_SIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FOSCODE
        {
            get
            {
                return this.FOSCODEField;
            }
            set
            {
                this.FOSCODEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Footware_SI
        {
            get
            {
                return this.Footware_SIField;
            }
            set
            {
                this.Footware_SIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Furniture_SI
        {
            get
            {
                return this.Furniture_SIField;
            }
            set
            {
                this.Furniture_SIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HealthCoupn
        {
            get
            {
                return this.HealthCoupnField;
            }
            set
            {
                this.HealthCoupnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kitchen_Appliances_SI
        {
            get
            {
                return this.Kitchen_Appliances_SIField;
            }
            set
            {
                this.Kitchen_Appliances_SIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LCCODE
        {
            get
            {
                return this.LCCODEField;
            }
            set
            {
                this.LCCODEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LGCODE
        {
            get
            {
                return this.LGCODEField;
            }
            set
            {
                this.LGCODEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LMSID
        {
            get
            {
                return this.LMSIDField;
            }
            set
            {
                this.LMSIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LOSCODE
        {
            get
            {
                return this.LOSCODEField;
            }
            set
            {
                this.LOSCODEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nominee_Name
        {
            get
            {
                return this.Nominee_NameField;
            }
            set
            {
                this.Nominee_NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nominee_Relation
        {
            get
            {
                return this.Nominee_RelationField;
            }
            set
            {
                this.Nominee_RelationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Other_Annexure_SI
        {
            get
            {
                return this.Other_Annexure_SIField;
            }
            set
            {
                this.Other_Annexure_SIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PolicyNumber
        {
            get
            {
                return this.PolicyNumberField;
            }
            set
            {
                this.PolicyNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Proposer_Country
        {
            get
            {
                return this.Proposer_CountryField;
            }
            set
            {
                this.Proposer_CountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Proposer_Qualification
        {
            get
            {
                return this.Proposer_QualificationField;
            }
            set
            {
                this.Proposer_QualificationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RelationshipType
        {
            get
            {
                return this.RelationshipTypeField;
            }
            set
            {
                this.RelationshipTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SAVINGACCNO
        {
            get
            {
                return this.SAVINGACCNOField;
            }
            set
            {
                this.SAVINGACCNOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SMCODE
        {
            get
            {
                return this.SMCODEField;
            }
            set
            {
                this.SMCODEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TPAName
        {
            get
            {
                return this.TPANameField;
            }
            set
            {
                this.TPANameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TP_POLICY_ENDDT
        {
            get
            {
                return this.TP_POLICY_ENDDTField;
            }
            set
            {
                this.TP_POLICY_ENDDTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TP_POLICY_INC
        {
            get
            {
                return this.TP_POLICY_INCField;
            }
            set
            {
                this.TP_POLICY_INCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TP_POLICY_NUMBER
        {
            get
            {
                return this.TP_POLICY_NUMBERField;
            }
            set
            {
                this.TP_POLICY_NUMBERField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TP_POLICY_STARTDT
        {
            get
            {
                return this.TP_POLICY_STARTDTField;
            }
            set
            {
                this.TP_POLICY_STARTDTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VerifiedID
        {
            get
            {
                return this.VerifiedIDField;
            }
            set
            {
                this.VerifiedIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Visa_Expiry_Dt
        {
            get
            {
                return this.Visa_Expiry_DtField;
            }
            set
            {
                this.Visa_Expiry_DtField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HDFCERGO.PIP.Adapters.OtherDetails.IOtherDetails")]
    public interface IOtherDetails
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOtherDetails/GetOtherDetailsObject", ReplyAction="http://tempuri.org/IOtherDetails/GetOtherDetailsObjectResponse")]
        HDFCERGO.PIP.Adapters.OtherDetails.GetOtherDetailsObjectResponse GetOtherDetailsObject(HDFCERGO.PIP.Adapters.OtherDetails.GetOtherDetailsObjectRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOtherDetails/GetOtherDetailsObject", ReplyAction="http://tempuri.org/IOtherDetails/GetOtherDetailsObjectResponse")]
        System.Threading.Tasks.Task<HDFCERGO.PIP.Adapters.OtherDetails.GetOtherDetailsObjectResponse> GetOtherDetailsObjectAsync(HDFCERGO.PIP.Adapters.OtherDetails.GetOtherDetailsObjectRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOtherDetailsObject", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetOtherDetailsObjectRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Prod_Code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public HDFCERGO.PIP.Adapters.OtherDetails.ClsInOut objInOut;
        
        public GetOtherDetailsObjectRequest()
        {
        }
        
        public GetOtherDetailsObjectRequest(string Prod_Code, HDFCERGO.PIP.Adapters.OtherDetails.ClsInOut objInOut)
        {
            this.Prod_Code = Prod_Code;
            this.objInOut = objInOut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOtherDetailsObjectResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetOtherDetailsObjectResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetOtherDetailsObjectResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public HDFCERGO.PIP.Adapters.OtherDetails.ClsInOut objInOut;
        
        public GetOtherDetailsObjectResponse()
        {
        }
        
        public GetOtherDetailsObjectResponse(string GetOtherDetailsObjectResult, HDFCERGO.PIP.Adapters.OtherDetails.ClsInOut objInOut)
        {
            this.GetOtherDetailsObjectResult = GetOtherDetailsObjectResult;
            this.objInOut = objInOut;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IOtherDetailsChannel : HDFCERGO.PIP.Adapters.OtherDetails.IOtherDetails, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class OtherDetailsClient : System.ServiceModel.ClientBase<HDFCERGO.PIP.Adapters.OtherDetails.IOtherDetails>, HDFCERGO.PIP.Adapters.OtherDetails.IOtherDetails
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public OtherDetailsClient() : 
                base(OtherDetailsClient.GetDefaultBinding(), OtherDetailsClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IOtherDetails.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OtherDetailsClient(EndpointConfiguration endpointConfiguration) : 
                base(OtherDetailsClient.GetBindingForEndpoint(endpointConfiguration), OtherDetailsClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OtherDetailsClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(OtherDetailsClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OtherDetailsClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(OtherDetailsClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OtherDetailsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HDFCERGO.PIP.Adapters.OtherDetails.GetOtherDetailsObjectResponse HDFCERGO.PIP.Adapters.OtherDetails.IOtherDetails.GetOtherDetailsObject(HDFCERGO.PIP.Adapters.OtherDetails.GetOtherDetailsObjectRequest request)
        {
            return base.Channel.GetOtherDetailsObject(request);
        }
        
        public string GetOtherDetailsObject(string Prod_Code, ref HDFCERGO.PIP.Adapters.OtherDetails.ClsInOut objInOut)
        {
            HDFCERGO.PIP.Adapters.OtherDetails.GetOtherDetailsObjectRequest inValue = new HDFCERGO.PIP.Adapters.OtherDetails.GetOtherDetailsObjectRequest();
            inValue.Prod_Code = Prod_Code;
            inValue.objInOut = objInOut;
            HDFCERGO.PIP.Adapters.OtherDetails.GetOtherDetailsObjectResponse retVal = ((HDFCERGO.PIP.Adapters.OtherDetails.IOtherDetails)(this)).GetOtherDetailsObject(inValue);
            objInOut = retVal.objInOut;
            return retVal.GetOtherDetailsObjectResult;
        }
        
        public System.Threading.Tasks.Task<HDFCERGO.PIP.Adapters.OtherDetails.GetOtherDetailsObjectResponse> GetOtherDetailsObjectAsync(HDFCERGO.PIP.Adapters.OtherDetails.GetOtherDetailsObjectRequest request)
        {
            return base.Channel.GetOtherDetailsObjectAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IOtherDetails))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IOtherDetails))
            {
                return new System.ServiceModel.EndpointAddress("http://uhepieif.hdfcergo.com/OtherDetailsService/OtherDetails.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return OtherDetailsClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IOtherDetails);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return OtherDetailsClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IOtherDetails);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IOtherDetails,
        }
    }
}
