//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDFCERGO.PIP.Adapters.HEPGService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HDFCERGO.PIP.Adapters.HEPGService.ServiceSoap")]
    public interface ServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPaymentModes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        HDFCERGO.PIP.Adapters.HEPGService.ArrayOfXElement GetPaymentModes(string producerCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPaymentModes", ReplyAction="*")]
        System.Threading.Tasks.Task<HDFCERGO.PIP.Adapters.HEPGService.ArrayOfXElement> GetPaymentModesAsync(string producerCode);
        
        // CODEGEN: Generating message contract since the wrapper name (GetPaymentModesWithAmount) of message GetPaymentModesWithAmount does not match the default value (GetPaymentModes1)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPaymentModesWithAmount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        HDFCERGO.PIP.Adapters.HEPGService.GetPaymentModesWithAmount1 GetPaymentModes1(HDFCERGO.PIP.Adapters.HEPGService.GetPaymentModesWithAmount request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPaymentModesWithAmount", ReplyAction="*")]
        System.Threading.Tasks.Task<HDFCERGO.PIP.Adapters.HEPGService.GetPaymentModesWithAmount1> GetPaymentModes1Async(HDFCERGO.PIP.Adapters.HEPGService.GetPaymentModesWithAmount request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetPaymentModesForSecondaryProducer) of message GetPaymentModesForSecondaryProducer does not match the default value (GetPaymentModes2)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPaymentModesForSecondaryProducer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        HDFCERGO.PIP.Adapters.HEPGService.GetPaymentModesForSecondaryProducer1 GetPaymentModes2(HDFCERGO.PIP.Adapters.HEPGService.GetPaymentModesForSecondaryProducer request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPaymentModesForSecondaryProducer", ReplyAction="*")]
        System.Threading.Tasks.Task<HDFCERGO.PIP.Adapters.HEPGService.GetPaymentModesForSecondaryProducer1> GetPaymentModes2Async(HDFCERGO.PIP.Adapters.HEPGService.GetPaymentModesForSecondaryProducer request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetPaymentModesForSecondaryProducerNProduct) of message GetPaymentModesForSecondaryProducerNProduct does not match the default value (GetPaymentModes3)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPaymentModesForSecondaryProducerNProduct", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        HDFCERGO.PIP.Adapters.HEPGService.GetPaymentModesForSecondaryProducerNProduct1 GetPaymentModes3(HDFCERGO.PIP.Adapters.HEPGService.GetPaymentModesForSecondaryProducerNProduct request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPaymentModesForSecondaryProducerNProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<HDFCERGO.PIP.Adapters.HEPGService.GetPaymentModesForSecondaryProducerNProduct1> GetPaymentModes3Async(HDFCERGO.PIP.Adapters.HEPGService.GetPaymentModesForSecondaryProducerNProduct request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPaymentURL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        HDFCERGO.PIP.Adapters.HEPGService.ArrayOfXElement GetPaymentURL(string producerCode, string PaymentMode, string EMIMode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPaymentURL", ReplyAction="*")]
        System.Threading.Tasks.Task<HDFCERGO.PIP.Adapters.HEPGService.ArrayOfXElement> GetPaymentURLAsync(string producerCode, string PaymentMode, string EMIMode);
        
        // CODEGEN: Generating message contract since the wrapper name (GetPaymentURLForProduct) of message GetPaymentURLForProduct does not match the default value (GetPaymentURL1)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPaymentURLForProduct", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        HDFCERGO.PIP.Adapters.HEPGService.GetPaymentURLForProduct1 GetPaymentURL1(HDFCERGO.PIP.Adapters.HEPGService.GetPaymentURLForProduct request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPaymentURLForProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<HDFCERGO.PIP.Adapters.HEPGService.GetPaymentURLForProduct1> GetPaymentURL1Async(HDFCERGO.PIP.Adapters.HEPGService.GetPaymentURLForProduct request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetPaymentURLForSecondaryProducer) of message GetPaymentURLForSecondaryProducer does not match the default value (GetPaymentURL2)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPaymentURLForSecondaryProducer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        HDFCERGO.PIP.Adapters.HEPGService.GetPaymentURLForSecondaryProducer1 GetPaymentURL2(HDFCERGO.PIP.Adapters.HEPGService.GetPaymentURLForSecondaryProducer request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPaymentURLForSecondaryProducer", ReplyAction="*")]
        System.Threading.Tasks.Task<HDFCERGO.PIP.Adapters.HEPGService.GetPaymentURLForSecondaryProducer1> GetPaymentURL2Async(HDFCERGO.PIP.Adapters.HEPGService.GetPaymentURLForSecondaryProducer request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMinimumAmountForEMI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        HDFCERGO.PIP.Adapters.HEPGService.ArrayOfXElement GetMinimumAmountForEMI(string producerCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMinimumAmountForEMI", ReplyAction="*")]
        System.Threading.Tasks.Task<HDFCERGO.PIP.Adapters.HEPGService.ArrayOfXElement> GetMinimumAmountForEMIAsync(string producerCode);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPaymentModesWithAmount", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPaymentModesWithAmount
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string producerCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public double PaymentAmount;
        
        public GetPaymentModesWithAmount()
        {
        }
        
        public GetPaymentModesWithAmount(string producerCode, double PaymentAmount)
        {
            this.producerCode = producerCode;
            this.PaymentAmount = PaymentAmount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPaymentModesWithAmountResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPaymentModesWithAmount1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public HDFCERGO.PIP.Adapters.HEPGService.ArrayOfXElement GetPaymentModesWithAmountResult;
        
        public GetPaymentModesWithAmount1()
        {
        }
        
        public GetPaymentModesWithAmount1(HDFCERGO.PIP.Adapters.HEPGService.ArrayOfXElement GetPaymentModesWithAmountResult)
        {
            this.GetPaymentModesWithAmountResult = GetPaymentModesWithAmountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPaymentModesForSecondaryProducer", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPaymentModesForSecondaryProducer
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string producerCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public double PaymentAmount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string SecondaryProducerCode;
        
        public GetPaymentModesForSecondaryProducer()
        {
        }
        
        public GetPaymentModesForSecondaryProducer(string producerCode, double PaymentAmount, string SecondaryProducerCode)
        {
            this.producerCode = producerCode;
            this.PaymentAmount = PaymentAmount;
            this.SecondaryProducerCode = SecondaryProducerCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPaymentModesForSecondaryProducerResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPaymentModesForSecondaryProducer1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public HDFCERGO.PIP.Adapters.HEPGService.ArrayOfXElement GetPaymentModesForSecondaryProducerResult;
        
        public GetPaymentModesForSecondaryProducer1()
        {
        }
        
        public GetPaymentModesForSecondaryProducer1(HDFCERGO.PIP.Adapters.HEPGService.ArrayOfXElement GetPaymentModesForSecondaryProducerResult)
        {
            this.GetPaymentModesForSecondaryProducerResult = GetPaymentModesForSecondaryProducerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPaymentModesForSecondaryProducerNProduct", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPaymentModesForSecondaryProducerNProduct
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string producerCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public double PaymentAmount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string SecondaryProducerCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string ProductCode;
        
        public GetPaymentModesForSecondaryProducerNProduct()
        {
        }
        
        public GetPaymentModesForSecondaryProducerNProduct(string producerCode, double PaymentAmount, string SecondaryProducerCode, string ProductCode)
        {
            this.producerCode = producerCode;
            this.PaymentAmount = PaymentAmount;
            this.SecondaryProducerCode = SecondaryProducerCode;
            this.ProductCode = ProductCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPaymentModesForSecondaryProducerNProductResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPaymentModesForSecondaryProducerNProduct1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public HDFCERGO.PIP.Adapters.HEPGService.ArrayOfXElement GetPaymentModesForSecondaryProducerNProductResult;
        
        public GetPaymentModesForSecondaryProducerNProduct1()
        {
        }
        
        public GetPaymentModesForSecondaryProducerNProduct1(HDFCERGO.PIP.Adapters.HEPGService.ArrayOfXElement GetPaymentModesForSecondaryProducerNProductResult)
        {
            this.GetPaymentModesForSecondaryProducerNProductResult = GetPaymentModesForSecondaryProducerNProductResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPaymentURLForProduct", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPaymentURLForProduct
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string producerCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string PaymentMode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string EMIMode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string ProductCode;
        
        public GetPaymentURLForProduct()
        {
        }
        
        public GetPaymentURLForProduct(string producerCode, string PaymentMode, string EMIMode, string ProductCode)
        {
            this.producerCode = producerCode;
            this.PaymentMode = PaymentMode;
            this.EMIMode = EMIMode;
            this.ProductCode = ProductCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPaymentURLForProductResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPaymentURLForProduct1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public HDFCERGO.PIP.Adapters.HEPGService.ArrayOfXElement GetPaymentURLForProductResult;
        
        public GetPaymentURLForProduct1()
        {
        }
        
        public GetPaymentURLForProduct1(HDFCERGO.PIP.Adapters.HEPGService.ArrayOfXElement GetPaymentURLForProductResult)
        {
            this.GetPaymentURLForProductResult = GetPaymentURLForProductResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPaymentURLForSecondaryProducer", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPaymentURLForSecondaryProducer
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string producerCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string PaymentMode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string EMIMode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string ProductCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string SecondaryProducerCode;
        
        public GetPaymentURLForSecondaryProducer()
        {
        }
        
        public GetPaymentURLForSecondaryProducer(string producerCode, string PaymentMode, string EMIMode, string ProductCode, string SecondaryProducerCode)
        {
            this.producerCode = producerCode;
            this.PaymentMode = PaymentMode;
            this.EMIMode = EMIMode;
            this.ProductCode = ProductCode;
            this.SecondaryProducerCode = SecondaryProducerCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPaymentURLForSecondaryProducerResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPaymentURLForSecondaryProducer1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public HDFCERGO.PIP.Adapters.HEPGService.ArrayOfXElement GetPaymentURLForSecondaryProducerResult;
        
        public GetPaymentURLForSecondaryProducer1()
        {
        }
        
        public GetPaymentURLForSecondaryProducer1(HDFCERGO.PIP.Adapters.HEPGService.ArrayOfXElement GetPaymentURLForSecondaryProducerResult)
        {
            this.GetPaymentURLForSecondaryProducerResult = GetPaymentURLForSecondaryProducerResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface ServiceSoapChannel : HDFCERGO.PIP.Adapters.HEPGService.ServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<HDFCERGO.PIP.Adapters.HEPGService.ServiceSoap>, HDFCERGO.PIP.Adapters.HEPGService.ServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), ServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public HDFCERGO.PIP.Adapters.HEPGService.ArrayOfXElement GetPaymentModes(string producerCode)
        {
            return base.Channel.GetPaymentModes(producerCode);
        }
        
        public System.Threading.Tasks.Task<HDFCERGO.PIP.Adapters.HEPGService.ArrayOfXElement> GetPaymentModesAsync(string producerCode)
        {
            return base.Channel.GetPaymentModesAsync(producerCode);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HDFCERGO.PIP.Adapters.HEPGService.GetPaymentModesWithAmount1 HDFCERGO.PIP.Adapters.HEPGService.ServiceSoap.GetPaymentModes1(HDFCERGO.PIP.Adapters.HEPGService.GetPaymentModesWithAmount request)
        {
            return base.Channel.GetPaymentModes1(request);
        }
        
        public HDFCERGO.PIP.Adapters.HEPGService.ArrayOfXElement GetPaymentModes1(string producerCode, double PaymentAmount)
        {
            HDFCERGO.PIP.Adapters.HEPGService.GetPaymentModesWithAmount inValue = new HDFCERGO.PIP.Adapters.HEPGService.GetPaymentModesWithAmount();
            inValue.producerCode = producerCode;
            inValue.PaymentAmount = PaymentAmount;
            HDFCERGO.PIP.Adapters.HEPGService.GetPaymentModesWithAmount1 retVal = ((HDFCERGO.PIP.Adapters.HEPGService.ServiceSoap)(this)).GetPaymentModes1(inValue);
            return retVal.GetPaymentModesWithAmountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HDFCERGO.PIP.Adapters.HEPGService.GetPaymentModesWithAmount1> HDFCERGO.PIP.Adapters.HEPGService.ServiceSoap.GetPaymentModes1Async(HDFCERGO.PIP.Adapters.HEPGService.GetPaymentModesWithAmount request)
        {
            return base.Channel.GetPaymentModes1Async(request);
        }
        
        public System.Threading.Tasks.Task<HDFCERGO.PIP.Adapters.HEPGService.GetPaymentModesWithAmount1> GetPaymentModes1Async(string producerCode, double PaymentAmount)
        {
            HDFCERGO.PIP.Adapters.HEPGService.GetPaymentModesWithAmount inValue = new HDFCERGO.PIP.Adapters.HEPGService.GetPaymentModesWithAmount();
            inValue.producerCode = producerCode;
            inValue.PaymentAmount = PaymentAmount;
            return ((HDFCERGO.PIP.Adapters.HEPGService.ServiceSoap)(this)).GetPaymentModes1Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HDFCERGO.PIP.Adapters.HEPGService.GetPaymentModesForSecondaryProducer1 HDFCERGO.PIP.Adapters.HEPGService.ServiceSoap.GetPaymentModes2(HDFCERGO.PIP.Adapters.HEPGService.GetPaymentModesForSecondaryProducer request)
        {
            return base.Channel.GetPaymentModes2(request);
        }
        
        public HDFCERGO.PIP.Adapters.HEPGService.ArrayOfXElement GetPaymentModes2(string producerCode, double PaymentAmount, string SecondaryProducerCode)
        {
            HDFCERGO.PIP.Adapters.HEPGService.GetPaymentModesForSecondaryProducer inValue = new HDFCERGO.PIP.Adapters.HEPGService.GetPaymentModesForSecondaryProducer();
            inValue.producerCode = producerCode;
            inValue.PaymentAmount = PaymentAmount;
            inValue.SecondaryProducerCode = SecondaryProducerCode;
            HDFCERGO.PIP.Adapters.HEPGService.GetPaymentModesForSecondaryProducer1 retVal = ((HDFCERGO.PIP.Adapters.HEPGService.ServiceSoap)(this)).GetPaymentModes2(inValue);
            return retVal.GetPaymentModesForSecondaryProducerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HDFCERGO.PIP.Adapters.HEPGService.GetPaymentModesForSecondaryProducer1> HDFCERGO.PIP.Adapters.HEPGService.ServiceSoap.GetPaymentModes2Async(HDFCERGO.PIP.Adapters.HEPGService.GetPaymentModesForSecondaryProducer request)
        {
            return base.Channel.GetPaymentModes2Async(request);
        }
        
        public System.Threading.Tasks.Task<HDFCERGO.PIP.Adapters.HEPGService.GetPaymentModesForSecondaryProducer1> GetPaymentModes2Async(string producerCode, double PaymentAmount, string SecondaryProducerCode)
        {
            HDFCERGO.PIP.Adapters.HEPGService.GetPaymentModesForSecondaryProducer inValue = new HDFCERGO.PIP.Adapters.HEPGService.GetPaymentModesForSecondaryProducer();
            inValue.producerCode = producerCode;
            inValue.PaymentAmount = PaymentAmount;
            inValue.SecondaryProducerCode = SecondaryProducerCode;
            return ((HDFCERGO.PIP.Adapters.HEPGService.ServiceSoap)(this)).GetPaymentModes2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HDFCERGO.PIP.Adapters.HEPGService.GetPaymentModesForSecondaryProducerNProduct1 HDFCERGO.PIP.Adapters.HEPGService.ServiceSoap.GetPaymentModes3(HDFCERGO.PIP.Adapters.HEPGService.GetPaymentModesForSecondaryProducerNProduct request)
        {
            return base.Channel.GetPaymentModes3(request);
        }
        
        public HDFCERGO.PIP.Adapters.HEPGService.ArrayOfXElement GetPaymentModes3(string producerCode, double PaymentAmount, string SecondaryProducerCode, string ProductCode)
        {
            HDFCERGO.PIP.Adapters.HEPGService.GetPaymentModesForSecondaryProducerNProduct inValue = new HDFCERGO.PIP.Adapters.HEPGService.GetPaymentModesForSecondaryProducerNProduct();
            inValue.producerCode = producerCode;
            inValue.PaymentAmount = PaymentAmount;
            inValue.SecondaryProducerCode = SecondaryProducerCode;
            inValue.ProductCode = ProductCode;
            HDFCERGO.PIP.Adapters.HEPGService.GetPaymentModesForSecondaryProducerNProduct1 retVal = ((HDFCERGO.PIP.Adapters.HEPGService.ServiceSoap)(this)).GetPaymentModes3(inValue);
            return retVal.GetPaymentModesForSecondaryProducerNProductResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HDFCERGO.PIP.Adapters.HEPGService.GetPaymentModesForSecondaryProducerNProduct1> HDFCERGO.PIP.Adapters.HEPGService.ServiceSoap.GetPaymentModes3Async(HDFCERGO.PIP.Adapters.HEPGService.GetPaymentModesForSecondaryProducerNProduct request)
        {
            return base.Channel.GetPaymentModes3Async(request);
        }
        
        public System.Threading.Tasks.Task<HDFCERGO.PIP.Adapters.HEPGService.GetPaymentModesForSecondaryProducerNProduct1> GetPaymentModes3Async(string producerCode, double PaymentAmount, string SecondaryProducerCode, string ProductCode)
        {
            HDFCERGO.PIP.Adapters.HEPGService.GetPaymentModesForSecondaryProducerNProduct inValue = new HDFCERGO.PIP.Adapters.HEPGService.GetPaymentModesForSecondaryProducerNProduct();
            inValue.producerCode = producerCode;
            inValue.PaymentAmount = PaymentAmount;
            inValue.SecondaryProducerCode = SecondaryProducerCode;
            inValue.ProductCode = ProductCode;
            return ((HDFCERGO.PIP.Adapters.HEPGService.ServiceSoap)(this)).GetPaymentModes3Async(inValue);
        }
        
        public HDFCERGO.PIP.Adapters.HEPGService.ArrayOfXElement GetPaymentURL(string producerCode, string PaymentMode, string EMIMode)
        {
            return base.Channel.GetPaymentURL(producerCode, PaymentMode, EMIMode);
        }
        
        public System.Threading.Tasks.Task<HDFCERGO.PIP.Adapters.HEPGService.ArrayOfXElement> GetPaymentURLAsync(string producerCode, string PaymentMode, string EMIMode)
        {
            return base.Channel.GetPaymentURLAsync(producerCode, PaymentMode, EMIMode);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HDFCERGO.PIP.Adapters.HEPGService.GetPaymentURLForProduct1 HDFCERGO.PIP.Adapters.HEPGService.ServiceSoap.GetPaymentURL1(HDFCERGO.PIP.Adapters.HEPGService.GetPaymentURLForProduct request)
        {
            return base.Channel.GetPaymentURL1(request);
        }
        
        public HDFCERGO.PIP.Adapters.HEPGService.ArrayOfXElement GetPaymentURL1(string producerCode, string PaymentMode, string EMIMode, string ProductCode)
        {
            HDFCERGO.PIP.Adapters.HEPGService.GetPaymentURLForProduct inValue = new HDFCERGO.PIP.Adapters.HEPGService.GetPaymentURLForProduct();
            inValue.producerCode = producerCode;
            inValue.PaymentMode = PaymentMode;
            inValue.EMIMode = EMIMode;
            inValue.ProductCode = ProductCode;
            HDFCERGO.PIP.Adapters.HEPGService.GetPaymentURLForProduct1 retVal = ((HDFCERGO.PIP.Adapters.HEPGService.ServiceSoap)(this)).GetPaymentURL1(inValue);
            return retVal.GetPaymentURLForProductResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HDFCERGO.PIP.Adapters.HEPGService.GetPaymentURLForProduct1> HDFCERGO.PIP.Adapters.HEPGService.ServiceSoap.GetPaymentURL1Async(HDFCERGO.PIP.Adapters.HEPGService.GetPaymentURLForProduct request)
        {
            return base.Channel.GetPaymentURL1Async(request);
        }
        
        public System.Threading.Tasks.Task<HDFCERGO.PIP.Adapters.HEPGService.GetPaymentURLForProduct1> GetPaymentURL1Async(string producerCode, string PaymentMode, string EMIMode, string ProductCode)
        {
            HDFCERGO.PIP.Adapters.HEPGService.GetPaymentURLForProduct inValue = new HDFCERGO.PIP.Adapters.HEPGService.GetPaymentURLForProduct();
            inValue.producerCode = producerCode;
            inValue.PaymentMode = PaymentMode;
            inValue.EMIMode = EMIMode;
            inValue.ProductCode = ProductCode;
            return ((HDFCERGO.PIP.Adapters.HEPGService.ServiceSoap)(this)).GetPaymentURL1Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HDFCERGO.PIP.Adapters.HEPGService.GetPaymentURLForSecondaryProducer1 HDFCERGO.PIP.Adapters.HEPGService.ServiceSoap.GetPaymentURL2(HDFCERGO.PIP.Adapters.HEPGService.GetPaymentURLForSecondaryProducer request)
        {
            return base.Channel.GetPaymentURL2(request);
        }
        
        public HDFCERGO.PIP.Adapters.HEPGService.ArrayOfXElement GetPaymentURL2(string producerCode, string PaymentMode, string EMIMode, string ProductCode, string SecondaryProducerCode)
        {
            HDFCERGO.PIP.Adapters.HEPGService.GetPaymentURLForSecondaryProducer inValue = new HDFCERGO.PIP.Adapters.HEPGService.GetPaymentURLForSecondaryProducer();
            inValue.producerCode = producerCode;
            inValue.PaymentMode = PaymentMode;
            inValue.EMIMode = EMIMode;
            inValue.ProductCode = ProductCode;
            inValue.SecondaryProducerCode = SecondaryProducerCode;
            HDFCERGO.PIP.Adapters.HEPGService.GetPaymentURLForSecondaryProducer1 retVal = ((HDFCERGO.PIP.Adapters.HEPGService.ServiceSoap)(this)).GetPaymentURL2(inValue);
            return retVal.GetPaymentURLForSecondaryProducerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HDFCERGO.PIP.Adapters.HEPGService.GetPaymentURLForSecondaryProducer1> HDFCERGO.PIP.Adapters.HEPGService.ServiceSoap.GetPaymentURL2Async(HDFCERGO.PIP.Adapters.HEPGService.GetPaymentURLForSecondaryProducer request)
        {
            return base.Channel.GetPaymentURL2Async(request);
        }
        
        public System.Threading.Tasks.Task<HDFCERGO.PIP.Adapters.HEPGService.GetPaymentURLForSecondaryProducer1> GetPaymentURL2Async(string producerCode, string PaymentMode, string EMIMode, string ProductCode, string SecondaryProducerCode)
        {
            HDFCERGO.PIP.Adapters.HEPGService.GetPaymentURLForSecondaryProducer inValue = new HDFCERGO.PIP.Adapters.HEPGService.GetPaymentURLForSecondaryProducer();
            inValue.producerCode = producerCode;
            inValue.PaymentMode = PaymentMode;
            inValue.EMIMode = EMIMode;
            inValue.ProductCode = ProductCode;
            inValue.SecondaryProducerCode = SecondaryProducerCode;
            return ((HDFCERGO.PIP.Adapters.HEPGService.ServiceSoap)(this)).GetPaymentURL2Async(inValue);
        }
        
        public HDFCERGO.PIP.Adapters.HEPGService.ArrayOfXElement GetMinimumAmountForEMI(string producerCode)
        {
            return base.Channel.GetMinimumAmountForEMI(producerCode);
        }
        
        public System.Threading.Tasks.Task<HDFCERGO.PIP.Adapters.HEPGService.ArrayOfXElement> GetMinimumAmountForEMIAsync(string producerCode)
        {
            return base.Channel.GetMinimumAmountForEMIAsync(producerCode);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://202.191.196.210/UAT/OnlineProducts/PaymentMode.WebService/Service.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://202.191.196.210/UAT/OnlineProducts/PaymentMode.WebService/Service.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ServiceSoap,
            
            ServiceSoap12,
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil-lib", "2.0.3.0")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement()
        {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes
        {
            get
            {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema()
        {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            )
            {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader)
        {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            )
            {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element))
                {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else
                {
                    reader.Skip();
                }
            }
        }
    }
}
