//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDFCERGO.PIP.Adapters.AMPortability
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoadingData", Namespace="http://schemas.datacontract.org/2004/07/OptimaCustomService")]
    public partial class LoadingData : object
    {
        
        private string ActiveFlagField;
        
        private string AmountField;
        
        private string BasicField;
        
        private string CoverNameField;
        
        private string InsertDateField;
        
        private string LoadingCodeField;
        
        private string LoadingReasonField;
        
        private string ModifyDateField;
        
        private string OtherReasonField;
        
        private string ProductCodeField;
        
        private string ProposalRefNoField;
        
        private string RateField;
        
        private string RefenceDateField;
        
        private string RiskSerialNoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActiveFlag
        {
            get
            {
                return this.ActiveFlagField;
            }
            set
            {
                this.ActiveFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Basic
        {
            get
            {
                return this.BasicField;
            }
            set
            {
                this.BasicField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CoverName
        {
            get
            {
                return this.CoverNameField;
            }
            set
            {
                this.CoverNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InsertDate
        {
            get
            {
                return this.InsertDateField;
            }
            set
            {
                this.InsertDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoadingCode
        {
            get
            {
                return this.LoadingCodeField;
            }
            set
            {
                this.LoadingCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoadingReason
        {
            get
            {
                return this.LoadingReasonField;
            }
            set
            {
                this.LoadingReasonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifyDate
        {
            get
            {
                return this.ModifyDateField;
            }
            set
            {
                this.ModifyDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OtherReason
        {
            get
            {
                return this.OtherReasonField;
            }
            set
            {
                this.OtherReasonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductCode
        {
            get
            {
                return this.ProductCodeField;
            }
            set
            {
                this.ProductCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProposalRefNo
        {
            get
            {
                return this.ProposalRefNoField;
            }
            set
            {
                this.ProposalRefNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rate
        {
            get
            {
                return this.RateField;
            }
            set
            {
                this.RateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RefenceDate
        {
            get
            {
                return this.RefenceDateField;
            }
            set
            {
                this.RefenceDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RiskSerialNo
        {
            get
            {
                return this.RiskSerialNoField;
            }
            set
            {
                this.RiskSerialNoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExclusionData", Namespace="http://schemas.datacontract.org/2004/07/OptimaCustomService")]
    public partial class ExclusionData : object
    {
        
        private string AffectsProdField;
        
        private string AutomaticReviewField;
        
        private string DateOfDiagnosisField;
        
        private string EndDateField;
        
        private string ExclusionTextField;
        
        private string ExclusionTypeField;
        
        private string InsertDateField;
        
        private string InsertTransIDField;
        
        private string LastConsultationDateField;
        
        private string MedCondDescField;
        
        private string MedCondNameField;
        
        private string MedCondStartDateField;
        
        private string PhyscologicalFuncField;
        
        private string ProductCodeField;
        
        private string ReferenceDateField;
        
        private string ReviewDateField;
        
        private string RiskNameField;
        
        private string RiskSrNOField;
        
        private string SiApplicableField;
        
        private string UserIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AffectsProd
        {
            get
            {
                return this.AffectsProdField;
            }
            set
            {
                this.AffectsProdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AutomaticReview
        {
            get
            {
                return this.AutomaticReviewField;
            }
            set
            {
                this.AutomaticReviewField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DateOfDiagnosis
        {
            get
            {
                return this.DateOfDiagnosisField;
            }
            set
            {
                this.DateOfDiagnosisField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndDate
        {
            get
            {
                return this.EndDateField;
            }
            set
            {
                this.EndDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExclusionText
        {
            get
            {
                return this.ExclusionTextField;
            }
            set
            {
                this.ExclusionTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExclusionType
        {
            get
            {
                return this.ExclusionTypeField;
            }
            set
            {
                this.ExclusionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InsertDate
        {
            get
            {
                return this.InsertDateField;
            }
            set
            {
                this.InsertDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InsertTransID
        {
            get
            {
                return this.InsertTransIDField;
            }
            set
            {
                this.InsertTransIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastConsultationDate
        {
            get
            {
                return this.LastConsultationDateField;
            }
            set
            {
                this.LastConsultationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MedCondDesc
        {
            get
            {
                return this.MedCondDescField;
            }
            set
            {
                this.MedCondDescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MedCondName
        {
            get
            {
                return this.MedCondNameField;
            }
            set
            {
                this.MedCondNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MedCondStartDate
        {
            get
            {
                return this.MedCondStartDateField;
            }
            set
            {
                this.MedCondStartDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhyscologicalFunc
        {
            get
            {
                return this.PhyscologicalFuncField;
            }
            set
            {
                this.PhyscologicalFuncField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductCode
        {
            get
            {
                return this.ProductCodeField;
            }
            set
            {
                this.ProductCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceDate
        {
            get
            {
                return this.ReferenceDateField;
            }
            set
            {
                this.ReferenceDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReviewDate
        {
            get
            {
                return this.ReviewDateField;
            }
            set
            {
                this.ReviewDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RiskName
        {
            get
            {
                return this.RiskNameField;
            }
            set
            {
                this.RiskNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RiskSrNO
        {
            get
            {
                return this.RiskSrNOField;
            }
            set
            {
                this.RiskSrNOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SiApplicable
        {
            get
            {
                return this.SiApplicableField;
            }
            set
            {
                this.SiApplicableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PortabilityData", Namespace="http://schemas.datacontract.org/2004/07/OptimaCustomService")]
    public partial class PortabilityData : object
    {
        
        private string ActiveFlagField;
        
        private string AnyRiderTakenField;
        
        private string CBField;
        
        private string ClaimLoggedField;
        
        private string ClaimRemarksField;
        
        private string CodeField;
        
        private string ConWaiverField;
        
        private string ContinuousField;
        
        private string EndDateField;
        
        private string EnhanceSIField;
        
        private string InsertDateField;
        
        private string InspectionDateField;
        
        private string ModifiedDateField;
        
        private string PEDOuPolperiodField;
        
        private string PEDWPolperiodField;
        
        private string PolicyNumberField;
        
        private string PreviousInsurerField;
        
        private string ProductCodeField;
        
        private string QualifyingAmountField;
        
        private string ReasonPortField;
        
        private string ReferenceDateField;
        
        private string ReferenceNumberField;
        
        private string RemarksField;
        
        private string RiskNameField;
        
        private string RiskSrlNoField;
        
        private string SumInsuredField;
        
        private string TransReferenceDateField;
        
        private string UniqueIdField;
        
        private string WavepPriodField;
        
        private string calculated_by_breField;
        
        private string continued_prebenefitsField;
        
        private string dateenrollmentField;
        
        private string isstpField;
        
        private string offline_unique_idField;
        
        private string policy_merging_allowedField;
        
        private string premium_paidField;
        
        private string prod_codeField;
        
        private string prod_descField;
        
        private string prodnameField;
        
        private string statusField;
        
        private string txt_codeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActiveFlag
        {
            get
            {
                return this.ActiveFlagField;
            }
            set
            {
                this.ActiveFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnyRiderTaken
        {
            get
            {
                return this.AnyRiderTakenField;
            }
            set
            {
                this.AnyRiderTakenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CB
        {
            get
            {
                return this.CBField;
            }
            set
            {
                this.CBField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaimLogged
        {
            get
            {
                return this.ClaimLoggedField;
            }
            set
            {
                this.ClaimLoggedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaimRemarks
        {
            get
            {
                return this.ClaimRemarksField;
            }
            set
            {
                this.ClaimRemarksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConWaiver
        {
            get
            {
                return this.ConWaiverField;
            }
            set
            {
                this.ConWaiverField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Continuous
        {
            get
            {
                return this.ContinuousField;
            }
            set
            {
                this.ContinuousField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndDate
        {
            get
            {
                return this.EndDateField;
            }
            set
            {
                this.EndDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnhanceSI
        {
            get
            {
                return this.EnhanceSIField;
            }
            set
            {
                this.EnhanceSIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InsertDate
        {
            get
            {
                return this.InsertDateField;
            }
            set
            {
                this.InsertDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InspectionDate
        {
            get
            {
                return this.InspectionDateField;
            }
            set
            {
                this.InspectionDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedDate
        {
            get
            {
                return this.ModifiedDateField;
            }
            set
            {
                this.ModifiedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PEDOuPolperiod
        {
            get
            {
                return this.PEDOuPolperiodField;
            }
            set
            {
                this.PEDOuPolperiodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PEDWPolperiod
        {
            get
            {
                return this.PEDWPolperiodField;
            }
            set
            {
                this.PEDWPolperiodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PolicyNumber
        {
            get
            {
                return this.PolicyNumberField;
            }
            set
            {
                this.PolicyNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreviousInsurer
        {
            get
            {
                return this.PreviousInsurerField;
            }
            set
            {
                this.PreviousInsurerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductCode
        {
            get
            {
                return this.ProductCodeField;
            }
            set
            {
                this.ProductCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QualifyingAmount
        {
            get
            {
                return this.QualifyingAmountField;
            }
            set
            {
                this.QualifyingAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReasonPort
        {
            get
            {
                return this.ReasonPortField;
            }
            set
            {
                this.ReasonPortField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceDate
        {
            get
            {
                return this.ReferenceDateField;
            }
            set
            {
                this.ReferenceDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceNumber
        {
            get
            {
                return this.ReferenceNumberField;
            }
            set
            {
                this.ReferenceNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remarks
        {
            get
            {
                return this.RemarksField;
            }
            set
            {
                this.RemarksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RiskName
        {
            get
            {
                return this.RiskNameField;
            }
            set
            {
                this.RiskNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RiskSrlNo
        {
            get
            {
                return this.RiskSrlNoField;
            }
            set
            {
                this.RiskSrlNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SumInsured
        {
            get
            {
                return this.SumInsuredField;
            }
            set
            {
                this.SumInsuredField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransReferenceDate
        {
            get
            {
                return this.TransReferenceDateField;
            }
            set
            {
                this.TransReferenceDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UniqueId
        {
            get
            {
                return this.UniqueIdField;
            }
            set
            {
                this.UniqueIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WavepPriod
        {
            get
            {
                return this.WavepPriodField;
            }
            set
            {
                this.WavepPriodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string calculated_by_bre
        {
            get
            {
                return this.calculated_by_breField;
            }
            set
            {
                this.calculated_by_breField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string continued_prebenefits
        {
            get
            {
                return this.continued_prebenefitsField;
            }
            set
            {
                this.continued_prebenefitsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dateenrollment
        {
            get
            {
                return this.dateenrollmentField;
            }
            set
            {
                this.dateenrollmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string isstp
        {
            get
            {
                return this.isstpField;
            }
            set
            {
                this.isstpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string offline_unique_id
        {
            get
            {
                return this.offline_unique_idField;
            }
            set
            {
                this.offline_unique_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string policy_merging_allowed
        {
            get
            {
                return this.policy_merging_allowedField;
            }
            set
            {
                this.policy_merging_allowedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string premium_paid
        {
            get
            {
                return this.premium_paidField;
            }
            set
            {
                this.premium_paidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string prod_code
        {
            get
            {
                return this.prod_codeField;
            }
            set
            {
                this.prod_codeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string prod_desc
        {
            get
            {
                return this.prod_descField;
            }
            set
            {
                this.prod_descField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string prodname
        {
            get
            {
                return this.prodnameField;
            }
            set
            {
                this.prodnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string txt_code
        {
            get
            {
                return this.txt_codeField;
            }
            set
            {
                this.txt_codeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LifestyleHabit", Namespace="http://schemas.datacontract.org/2004/07/OptimaCustomService")]
    public partial class LifestyleHabit : object
    {
        
        private string HabitNameField;
        
        private string HabitOptionField;
        
        private string HabitPerDayField;
        
        private string HabitPerMonthField;
        
        private string HabitPerWeekField;
        
        private string HabitSinceHowManyYearsField;
        
        private string InsertDateField;
        
        private string InsertTransIDField;
        
        private string ProductCodeField;
        
        private string ReferenceDateField;
        
        private string ReferenceNumberField;
        
        private string RiskNameField;
        
        private string RiskSrNOField;
        
        private string offline_unique_idField;
        
        private string risk_member_idField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HabitName
        {
            get
            {
                return this.HabitNameField;
            }
            set
            {
                this.HabitNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HabitOption
        {
            get
            {
                return this.HabitOptionField;
            }
            set
            {
                this.HabitOptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HabitPerDay
        {
            get
            {
                return this.HabitPerDayField;
            }
            set
            {
                this.HabitPerDayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HabitPerMonth
        {
            get
            {
                return this.HabitPerMonthField;
            }
            set
            {
                this.HabitPerMonthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HabitPerWeek
        {
            get
            {
                return this.HabitPerWeekField;
            }
            set
            {
                this.HabitPerWeekField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HabitSinceHowManyYears
        {
            get
            {
                return this.HabitSinceHowManyYearsField;
            }
            set
            {
                this.HabitSinceHowManyYearsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InsertDate
        {
            get
            {
                return this.InsertDateField;
            }
            set
            {
                this.InsertDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InsertTransID
        {
            get
            {
                return this.InsertTransIDField;
            }
            set
            {
                this.InsertTransIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductCode
        {
            get
            {
                return this.ProductCodeField;
            }
            set
            {
                this.ProductCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceDate
        {
            get
            {
                return this.ReferenceDateField;
            }
            set
            {
                this.ReferenceDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceNumber
        {
            get
            {
                return this.ReferenceNumberField;
            }
            set
            {
                this.ReferenceNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RiskName
        {
            get
            {
                return this.RiskNameField;
            }
            set
            {
                this.RiskNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RiskSrNO
        {
            get
            {
                return this.RiskSrNOField;
            }
            set
            {
                this.RiskSrNOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string offline_unique_id
        {
            get
            {
                return this.offline_unique_idField;
            }
            set
            {
                this.offline_unique_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string risk_member_id
        {
            get
            {
                return this.risk_member_idField;
            }
            set
            {
                this.risk_member_idField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HDFCERGO.PIP.Adapters.AMPortability.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addLoading", ReplyAction="http://tempuri.org/IService1/addLoadingResponse")]
        string addLoading(string OfflineQuoteNO, HDFCERGO.PIP.Adapters.AMPortability.LoadingData[] loadingData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addLoading", ReplyAction="http://tempuri.org/IService1/addLoadingResponse")]
        System.Threading.Tasks.Task<string> addLoadingAsync(string OfflineQuoteNO, HDFCERGO.PIP.Adapters.AMPortability.LoadingData[] loadingData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addExclusion", ReplyAction="http://tempuri.org/IService1/addExclusionResponse")]
        string addExclusion(string OfflineQuoteNO, HDFCERGO.PIP.Adapters.AMPortability.ExclusionData[] exclusionData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addExclusion", ReplyAction="http://tempuri.org/IService1/addExclusionResponse")]
        System.Threading.Tasks.Task<string> addExclusionAsync(string OfflineQuoteNO, HDFCERGO.PIP.Adapters.AMPortability.ExclusionData[] exclusionData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addPortability", ReplyAction="http://tempuri.org/IService1/addPortabilityResponse")]
        string addPortability(string OfflineQuoteNO, HDFCERGO.PIP.Adapters.AMPortability.PortabilityData[] portabilityData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addPortability", ReplyAction="http://tempuri.org/IService1/addPortabilityResponse")]
        System.Threading.Tasks.Task<string> addPortabilityAsync(string OfflineQuoteNO, HDFCERGO.PIP.Adapters.AMPortability.PortabilityData[] portabilityData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getLoading", ReplyAction="http://tempuri.org/IService1/getLoadingResponse")]
        HDFCERGO.PIP.Adapters.AMPortability.LoadingData[] getLoading(string proposalNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getLoading", ReplyAction="http://tempuri.org/IService1/getLoadingResponse")]
        System.Threading.Tasks.Task<HDFCERGO.PIP.Adapters.AMPortability.LoadingData[]> getLoadingAsync(string proposalNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getExclusion", ReplyAction="http://tempuri.org/IService1/getExclusionResponse")]
        HDFCERGO.PIP.Adapters.AMPortability.ExclusionData[] getExclusion(string proposalNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getExclusion", ReplyAction="http://tempuri.org/IService1/getExclusionResponse")]
        System.Threading.Tasks.Task<HDFCERGO.PIP.Adapters.AMPortability.ExclusionData[]> getExclusionAsync(string proposalNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getPortability", ReplyAction="http://tempuri.org/IService1/getPortabilityResponse")]
        HDFCERGO.PIP.Adapters.AMPortability.PortabilityData[] getPortability(string proposalNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getPortability", ReplyAction="http://tempuri.org/IService1/getPortabilityResponse")]
        System.Threading.Tasks.Task<HDFCERGO.PIP.Adapters.AMPortability.PortabilityData[]> getPortabilityAsync(string proposalNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addLifestyleHabit", ReplyAction="http://tempuri.org/IService1/addLifestyleHabitResponse")]
        string addLifestyleHabit(string OfflineQuoteNO, HDFCERGO.PIP.Adapters.AMPortability.LifestyleHabit[] LifestyleHabitData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addLifestyleHabit", ReplyAction="http://tempuri.org/IService1/addLifestyleHabitResponse")]
        System.Threading.Tasks.Task<string> addLifestyleHabitAsync(string OfflineQuoteNO, HDFCERGO.PIP.Adapters.AMPortability.LifestyleHabit[] LifestyleHabitData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getLifeStyle", ReplyAction="http://tempuri.org/IService1/getLifeStyleResponse")]
        HDFCERGO.PIP.Adapters.AMPortability.LifestyleHabit[] getLifeStyle(string proposalNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getLifeStyle", ReplyAction="http://tempuri.org/IService1/getLifeStyleResponse")]
        System.Threading.Tasks.Task<HDFCERGO.PIP.Adapters.AMPortability.LifestyleHabit[]> getLifeStyleAsync(string proposalNo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IService1Channel : HDFCERGO.PIP.Adapters.AMPortability.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class Service1Client : System.ServiceModel.ClientBase<HDFCERGO.PIP.Adapters.AMPortability.IService1>, HDFCERGO.PIP.Adapters.AMPortability.IService1
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public string addLoading(string OfflineQuoteNO, HDFCERGO.PIP.Adapters.AMPortability.LoadingData[] loadingData)
        {
            return base.Channel.addLoading(OfflineQuoteNO, loadingData);
        }
        
        public System.Threading.Tasks.Task<string> addLoadingAsync(string OfflineQuoteNO, HDFCERGO.PIP.Adapters.AMPortability.LoadingData[] loadingData)
        {
            return base.Channel.addLoadingAsync(OfflineQuoteNO, loadingData);
        }
        
        public string addExclusion(string OfflineQuoteNO, HDFCERGO.PIP.Adapters.AMPortability.ExclusionData[] exclusionData)
        {
            return base.Channel.addExclusion(OfflineQuoteNO, exclusionData);
        }
        
        public System.Threading.Tasks.Task<string> addExclusionAsync(string OfflineQuoteNO, HDFCERGO.PIP.Adapters.AMPortability.ExclusionData[] exclusionData)
        {
            return base.Channel.addExclusionAsync(OfflineQuoteNO, exclusionData);
        }
        
        public string addPortability(string OfflineQuoteNO, HDFCERGO.PIP.Adapters.AMPortability.PortabilityData[] portabilityData)
        {
            return base.Channel.addPortability(OfflineQuoteNO, portabilityData);
        }
        
        public System.Threading.Tasks.Task<string> addPortabilityAsync(string OfflineQuoteNO, HDFCERGO.PIP.Adapters.AMPortability.PortabilityData[] portabilityData)
        {
            return base.Channel.addPortabilityAsync(OfflineQuoteNO, portabilityData);
        }
        
        public HDFCERGO.PIP.Adapters.AMPortability.LoadingData[] getLoading(string proposalNo)
        {
            return base.Channel.getLoading(proposalNo);
        }
        
        public System.Threading.Tasks.Task<HDFCERGO.PIP.Adapters.AMPortability.LoadingData[]> getLoadingAsync(string proposalNo)
        {
            return base.Channel.getLoadingAsync(proposalNo);
        }
        
        public HDFCERGO.PIP.Adapters.AMPortability.ExclusionData[] getExclusion(string proposalNo)
        {
            return base.Channel.getExclusion(proposalNo);
        }
        
        public System.Threading.Tasks.Task<HDFCERGO.PIP.Adapters.AMPortability.ExclusionData[]> getExclusionAsync(string proposalNo)
        {
            return base.Channel.getExclusionAsync(proposalNo);
        }
        
        public HDFCERGO.PIP.Adapters.AMPortability.PortabilityData[] getPortability(string proposalNo)
        {
            return base.Channel.getPortability(proposalNo);
        }
        
        public System.Threading.Tasks.Task<HDFCERGO.PIP.Adapters.AMPortability.PortabilityData[]> getPortabilityAsync(string proposalNo)
        {
            return base.Channel.getPortabilityAsync(proposalNo);
        }
        
        public string addLifestyleHabit(string OfflineQuoteNO, HDFCERGO.PIP.Adapters.AMPortability.LifestyleHabit[] LifestyleHabitData)
        {
            return base.Channel.addLifestyleHabit(OfflineQuoteNO, LifestyleHabitData);
        }
        
        public System.Threading.Tasks.Task<string> addLifestyleHabitAsync(string OfflineQuoteNO, HDFCERGO.PIP.Adapters.AMPortability.LifestyleHabit[] LifestyleHabitData)
        {
            return base.Channel.addLifestyleHabitAsync(OfflineQuoteNO, LifestyleHabitData);
        }
        
        public HDFCERGO.PIP.Adapters.AMPortability.LifestyleHabit[] getLifeStyle(string proposalNo)
        {
            return base.Channel.getLifeStyle(proposalNo);
        }
        
        public System.Threading.Tasks.Task<HDFCERGO.PIP.Adapters.AMPortability.LifestyleHabit[]> getLifeStyleAsync(string proposalNo)
        {
            return base.Channel.getLifeStyleAsync(proposalNo);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                return new System.ServiceModel.EndpointAddress("http://uhepieif.hdfcergo.com/OptimaCustomWCFService/OptimaCustomWCFSvc.OptimaCust" +
                        "om.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService1,
        }
    }
}
