//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDFCERGO.PIP.Adapters.BreakIn
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InitiationEntity", Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    public partial class InitiationEntity : object
    {
        
        private string AMSUserField;
        
        private int ActionStatusField;
        
        private string Address1Field;
        
        private string Address2Field;
        
        private int BreakinIdField;
        
        private string ChassisField;
        
        private string CityField;
        
        private int CityIdField;
        
        private string ContantPersonField;
        
        private string CustFirstNameField;
        
        private string CustLastNameField;
        
        private int CustomerIdField;
        
        private string CustomerLocationField;
        
        private string DepartmentField;
        
        private int DepartmentIdField;
        
        private string DocumentNameField;
        
        private string DocumentTypeField;
        
        private string EngineField;
        
        private string FDateField;
        
        private string FileExtensionField;
        
        private long FileIDField;
        
        private string InitationReasonIDField;
        
        private string InitiatedByField;
        
        private System.DateTime InitiationDateField;
        
        private string InitiationReasonField;
        
        private string InitiationRemarksField;
        
        private string InitiationStatusField;
        
        private string InsSaveDateField;
        
        private string InspectionDateField;
        
        private string InspectionReasonField;
        
        private string InspectionReasonIDField;
        
        private string InspectionTimeField;
        
        private string InsuredEmailIdField;
        
        private string InsuredMobileField;
        
        private string InsuredNameField;
        
        private int InsurerIdField;
        
        private string IsRecommendedField;
        
        private int Is_Doc_UploadedField;
        
        private string LocationField;
        
        private string LogField;
        
        private string MakeField;
        
        private string MakeCPMField;
        
        private int MakeModelIDField;
        
        private string MobileField;
        
        private string ModelField;
        
        private string ModelCPMField;
        
        private int ModelIdField;
        
        private string NewPolicyNoField;
        
        private string OrionAddress1Field;
        
        private string OrionAddress2Field;
        
        private int OrionChkBoxField;
        
        private int OrionCityIdField;
        
        private int OrionLocationIdField;
        
        private string OrionMobileNoField;
        
        private int OrionPincodeField;
        
        private string OrionPremiumAmountField;
        
        private int PHOTO_UPLOADEDField;
        
        private string Param1Field;
        
        private string Param2Field;
        
        private string PhoneField;
        
        private string PincodeField;
        
        private System.DateTime PolicyEndDateField;
        
        private int PolicyIdField;
        
        private string PolicyNoField;
        
        private string PortalTranscNoField;
        
        private string ProductTypeField;
        
        private int ProductTypeIdField;
        
        private string ProprosalField;
        
        private int REPORT_UPLOADEDField;
        
        private string RFirstNameField;
        
        private string RLastNameField;
        
        private string RMEmailField;
        
        private string RTOCityField;
        
        private string RTOCityIDField;
        
        private string RTOLocationField;
        
        private int RTOLocationIdField;
        
        private string RTOStateField;
        
        private string RegField;
        
        private string Reg1Field;
        
        private string Reg2Field;
        
        private string Reg3Field;
        
        private string Reg4Field;
        
        private string SerialNoField;
        
        private string SourceCodeField;
        
        private string StateField;
        
        private int StatusField;
        
        private string SubDepartmentField;
        
        private int SubDepartmentIdField;
        
        private string TDateField;
        
        private System.DateTime TPAAssignDateField;
        
        private int TPAIDField;
        
        private string TPARemarksField;
        
        private string TPAUserIdField;
        
        private int TotalRemarksField;
        
        private string TypeField;
        
        private int UpdateTypeField;
        
        private string UploadedTimeField;
        
        private string VehChsField;
        
        private string VehEngField;
        
        private string VehRegistrationNoField;
        
        private string VehSerialNoField;
        
        private int VehicleIdField;
        
        private string VehicleTypeField;
        
        private string VehicleVariantField;
        
        private int WorkFlowIdField;
        
        private string YearField;
        
        private int locationIdField;
        
        private string msStatField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AMSUser
        {
            get
            {
                return this.AMSUserField;
            }
            set
            {
                this.AMSUserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ActionStatus
        {
            get
            {
                return this.ActionStatusField;
            }
            set
            {
                this.ActionStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address1
        {
            get
            {
                return this.Address1Field;
            }
            set
            {
                this.Address1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address2
        {
            get
            {
                return this.Address2Field;
            }
            set
            {
                this.Address2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BreakinId
        {
            get
            {
                return this.BreakinIdField;
            }
            set
            {
                this.BreakinIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Chassis
        {
            get
            {
                return this.ChassisField;
            }
            set
            {
                this.ChassisField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CityId
        {
            get
            {
                return this.CityIdField;
            }
            set
            {
                this.CityIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContantPerson
        {
            get
            {
                return this.ContantPersonField;
            }
            set
            {
                this.ContantPersonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustFirstName
        {
            get
            {
                return this.CustFirstNameField;
            }
            set
            {
                this.CustFirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustLastName
        {
            get
            {
                return this.CustLastNameField;
            }
            set
            {
                this.CustLastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId
        {
            get
            {
                return this.CustomerIdField;
            }
            set
            {
                this.CustomerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerLocation
        {
            get
            {
                return this.CustomerLocationField;
            }
            set
            {
                this.CustomerLocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Department
        {
            get
            {
                return this.DepartmentField;
            }
            set
            {
                this.DepartmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DepartmentId
        {
            get
            {
                return this.DepartmentIdField;
            }
            set
            {
                this.DepartmentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentName
        {
            get
            {
                return this.DocumentNameField;
            }
            set
            {
                this.DocumentNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentType
        {
            get
            {
                return this.DocumentTypeField;
            }
            set
            {
                this.DocumentTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Engine
        {
            get
            {
                return this.EngineField;
            }
            set
            {
                this.EngineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FDate
        {
            get
            {
                return this.FDateField;
            }
            set
            {
                this.FDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileExtension
        {
            get
            {
                return this.FileExtensionField;
            }
            set
            {
                this.FileExtensionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long FileID
        {
            get
            {
                return this.FileIDField;
            }
            set
            {
                this.FileIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InitationReasonID
        {
            get
            {
                return this.InitationReasonIDField;
            }
            set
            {
                this.InitationReasonIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InitiatedBy
        {
            get
            {
                return this.InitiatedByField;
            }
            set
            {
                this.InitiatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InitiationDate
        {
            get
            {
                return this.InitiationDateField;
            }
            set
            {
                this.InitiationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InitiationReason
        {
            get
            {
                return this.InitiationReasonField;
            }
            set
            {
                this.InitiationReasonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InitiationRemarks
        {
            get
            {
                return this.InitiationRemarksField;
            }
            set
            {
                this.InitiationRemarksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InitiationStatus
        {
            get
            {
                return this.InitiationStatusField;
            }
            set
            {
                this.InitiationStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InsSaveDate
        {
            get
            {
                return this.InsSaveDateField;
            }
            set
            {
                this.InsSaveDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InspectionDate
        {
            get
            {
                return this.InspectionDateField;
            }
            set
            {
                this.InspectionDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InspectionReason
        {
            get
            {
                return this.InspectionReasonField;
            }
            set
            {
                this.InspectionReasonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InspectionReasonID
        {
            get
            {
                return this.InspectionReasonIDField;
            }
            set
            {
                this.InspectionReasonIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InspectionTime
        {
            get
            {
                return this.InspectionTimeField;
            }
            set
            {
                this.InspectionTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InsuredEmailId
        {
            get
            {
                return this.InsuredEmailIdField;
            }
            set
            {
                this.InsuredEmailIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InsuredMobile
        {
            get
            {
                return this.InsuredMobileField;
            }
            set
            {
                this.InsuredMobileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InsuredName
        {
            get
            {
                return this.InsuredNameField;
            }
            set
            {
                this.InsuredNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InsurerId
        {
            get
            {
                return this.InsurerIdField;
            }
            set
            {
                this.InsurerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsRecommended
        {
            get
            {
                return this.IsRecommendedField;
            }
            set
            {
                this.IsRecommendedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Is_Doc_Uploaded
        {
            get
            {
                return this.Is_Doc_UploadedField;
            }
            set
            {
                this.Is_Doc_UploadedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location
        {
            get
            {
                return this.LocationField;
            }
            set
            {
                this.LocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Log
        {
            get
            {
                return this.LogField;
            }
            set
            {
                this.LogField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Make
        {
            get
            {
                return this.MakeField;
            }
            set
            {
                this.MakeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MakeCPM
        {
            get
            {
                return this.MakeCPMField;
            }
            set
            {
                this.MakeCPMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MakeModelID
        {
            get
            {
                return this.MakeModelIDField;
            }
            set
            {
                this.MakeModelIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile
        {
            get
            {
                return this.MobileField;
            }
            set
            {
                this.MobileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model
        {
            get
            {
                return this.ModelField;
            }
            set
            {
                this.ModelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModelCPM
        {
            get
            {
                return this.ModelCPMField;
            }
            set
            {
                this.ModelCPMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ModelId
        {
            get
            {
                return this.ModelIdField;
            }
            set
            {
                this.ModelIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewPolicyNo
        {
            get
            {
                return this.NewPolicyNoField;
            }
            set
            {
                this.NewPolicyNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrionAddress1
        {
            get
            {
                return this.OrionAddress1Field;
            }
            set
            {
                this.OrionAddress1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrionAddress2
        {
            get
            {
                return this.OrionAddress2Field;
            }
            set
            {
                this.OrionAddress2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrionChkBox
        {
            get
            {
                return this.OrionChkBoxField;
            }
            set
            {
                this.OrionChkBoxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrionCityId
        {
            get
            {
                return this.OrionCityIdField;
            }
            set
            {
                this.OrionCityIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrionLocationId
        {
            get
            {
                return this.OrionLocationIdField;
            }
            set
            {
                this.OrionLocationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrionMobileNo
        {
            get
            {
                return this.OrionMobileNoField;
            }
            set
            {
                this.OrionMobileNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrionPincode
        {
            get
            {
                return this.OrionPincodeField;
            }
            set
            {
                this.OrionPincodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrionPremiumAmount
        {
            get
            {
                return this.OrionPremiumAmountField;
            }
            set
            {
                this.OrionPremiumAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PHOTO_UPLOADED
        {
            get
            {
                return this.PHOTO_UPLOADEDField;
            }
            set
            {
                this.PHOTO_UPLOADEDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param1
        {
            get
            {
                return this.Param1Field;
            }
            set
            {
                this.Param1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param2
        {
            get
            {
                return this.Param2Field;
            }
            set
            {
                this.Param2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pincode
        {
            get
            {
                return this.PincodeField;
            }
            set
            {
                this.PincodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PolicyEndDate
        {
            get
            {
                return this.PolicyEndDateField;
            }
            set
            {
                this.PolicyEndDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PolicyId
        {
            get
            {
                return this.PolicyIdField;
            }
            set
            {
                this.PolicyIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PolicyNo
        {
            get
            {
                return this.PolicyNoField;
            }
            set
            {
                this.PolicyNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PortalTranscNo
        {
            get
            {
                return this.PortalTranscNoField;
            }
            set
            {
                this.PortalTranscNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductType
        {
            get
            {
                return this.ProductTypeField;
            }
            set
            {
                this.ProductTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductTypeId
        {
            get
            {
                return this.ProductTypeIdField;
            }
            set
            {
                this.ProductTypeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Proprosal
        {
            get
            {
                return this.ProprosalField;
            }
            set
            {
                this.ProprosalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int REPORT_UPLOADED
        {
            get
            {
                return this.REPORT_UPLOADEDField;
            }
            set
            {
                this.REPORT_UPLOADEDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RFirstName
        {
            get
            {
                return this.RFirstNameField;
            }
            set
            {
                this.RFirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RLastName
        {
            get
            {
                return this.RLastNameField;
            }
            set
            {
                this.RLastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RMEmail
        {
            get
            {
                return this.RMEmailField;
            }
            set
            {
                this.RMEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RTOCity
        {
            get
            {
                return this.RTOCityField;
            }
            set
            {
                this.RTOCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RTOCityID
        {
            get
            {
                return this.RTOCityIDField;
            }
            set
            {
                this.RTOCityIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RTOLocation
        {
            get
            {
                return this.RTOLocationField;
            }
            set
            {
                this.RTOLocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RTOLocationId
        {
            get
            {
                return this.RTOLocationIdField;
            }
            set
            {
                this.RTOLocationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RTOState
        {
            get
            {
                return this.RTOStateField;
            }
            set
            {
                this.RTOStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reg
        {
            get
            {
                return this.RegField;
            }
            set
            {
                this.RegField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reg1
        {
            get
            {
                return this.Reg1Field;
            }
            set
            {
                this.Reg1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reg2
        {
            get
            {
                return this.Reg2Field;
            }
            set
            {
                this.Reg2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reg3
        {
            get
            {
                return this.Reg3Field;
            }
            set
            {
                this.Reg3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reg4
        {
            get
            {
                return this.Reg4Field;
            }
            set
            {
                this.Reg4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerialNo
        {
            get
            {
                return this.SerialNoField;
            }
            set
            {
                this.SerialNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SourceCode
        {
            get
            {
                return this.SourceCodeField;
            }
            set
            {
                this.SourceCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubDepartment
        {
            get
            {
                return this.SubDepartmentField;
            }
            set
            {
                this.SubDepartmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SubDepartmentId
        {
            get
            {
                return this.SubDepartmentIdField;
            }
            set
            {
                this.SubDepartmentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TDate
        {
            get
            {
                return this.TDateField;
            }
            set
            {
                this.TDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TPAAssignDate
        {
            get
            {
                return this.TPAAssignDateField;
            }
            set
            {
                this.TPAAssignDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TPAID
        {
            get
            {
                return this.TPAIDField;
            }
            set
            {
                this.TPAIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TPARemarks
        {
            get
            {
                return this.TPARemarksField;
            }
            set
            {
                this.TPARemarksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TPAUserId
        {
            get
            {
                return this.TPAUserIdField;
            }
            set
            {
                this.TPAUserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRemarks
        {
            get
            {
                return this.TotalRemarksField;
            }
            set
            {
                this.TotalRemarksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UpdateType
        {
            get
            {
                return this.UpdateTypeField;
            }
            set
            {
                this.UpdateTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UploadedTime
        {
            get
            {
                return this.UploadedTimeField;
            }
            set
            {
                this.UploadedTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VehChs
        {
            get
            {
                return this.VehChsField;
            }
            set
            {
                this.VehChsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VehEng
        {
            get
            {
                return this.VehEngField;
            }
            set
            {
                this.VehEngField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VehRegistrationNo
        {
            get
            {
                return this.VehRegistrationNoField;
            }
            set
            {
                this.VehRegistrationNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VehSerialNo
        {
            get
            {
                return this.VehSerialNoField;
            }
            set
            {
                this.VehSerialNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VehicleId
        {
            get
            {
                return this.VehicleIdField;
            }
            set
            {
                this.VehicleIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VehicleType
        {
            get
            {
                return this.VehicleTypeField;
            }
            set
            {
                this.VehicleTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VehicleVariant
        {
            get
            {
                return this.VehicleVariantField;
            }
            set
            {
                this.VehicleVariantField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WorkFlowId
        {
            get
            {
                return this.WorkFlowIdField;
            }
            set
            {
                this.WorkFlowIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Year
        {
            get
            {
                return this.YearField;
            }
            set
            {
                this.YearField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int locationId
        {
            get
            {
                return this.locationIdField;
            }
            set
            {
                this.locationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string msStat
        {
            get
            {
                return this.msStatField;
            }
            set
            {
                this.msStatField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HDFCERGO.PIP.Adapters.BreakIn.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBreakinID", ReplyAction="http://tempuri.org/IService1/GetBreakinIDResponse")]
        string GetBreakinID(HDFCERGO.PIP.Adapters.BreakIn.InitiationEntity objInitEntity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBreakinID", ReplyAction="http://tempuri.org/IService1/GetBreakinIDResponse")]
        System.Threading.Tasks.Task<string> GetBreakinIDAsync(HDFCERGO.PIP.Adapters.BreakIn.InitiationEntity objInitEntity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBreakinStatus", ReplyAction="http://tempuri.org/IService1/GetBreakinStatusResponse")]
        string GetBreakinStatus(int BrakinID, string RegNo, string InspectionDate, string UserType, string DisInspectionDate, string BusinessType, string Vertical, string Policy_StartDate, string Remark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBreakinStatus", ReplyAction="http://tempuri.org/IService1/GetBreakinStatusResponse")]
        System.Threading.Tasks.Task<string> GetBreakinStatusAsync(int BrakinID, string RegNo, string InspectionDate, string UserType, string DisInspectionDate, string BusinessType, string Vertical, string Policy_StartDate, string Remark);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IService1Channel : HDFCERGO.PIP.Adapters.BreakIn.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class Service1Client : System.ServiceModel.ClientBase<HDFCERGO.PIP.Adapters.BreakIn.IService1>, HDFCERGO.PIP.Adapters.BreakIn.IService1
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public string GetBreakinID(HDFCERGO.PIP.Adapters.BreakIn.InitiationEntity objInitEntity)
        {
            return base.Channel.GetBreakinID(objInitEntity);
        }
        
        public System.Threading.Tasks.Task<string> GetBreakinIDAsync(HDFCERGO.PIP.Adapters.BreakIn.InitiationEntity objInitEntity)
        {
            return base.Channel.GetBreakinIDAsync(objInitEntity);
        }
        
        public string GetBreakinStatus(int BrakinID, string RegNo, string InspectionDate, string UserType, string DisInspectionDate, string BusinessType, string Vertical, string Policy_StartDate, string Remark)
        {
            return base.Channel.GetBreakinStatus(BrakinID, RegNo, InspectionDate, UserType, DisInspectionDate, BusinessType, Vertical, Policy_StartDate, Remark);
        }
        
        public System.Threading.Tasks.Task<string> GetBreakinStatusAsync(int BrakinID, string RegNo, string InspectionDate, string UserType, string DisInspectionDate, string BusinessType, string Vertical, string Policy_StartDate, string Remark)
        {
            return base.Channel.GetBreakinStatusAsync(BrakinID, RegNo, InspectionDate, UserType, DisInspectionDate, BusinessType, Vertical, Policy_StartDate, Remark);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                return new System.ServiceModel.EndpointAddress("http://115.113.35.240/Breakinwrapperservice/BreakinWrapper_WCF.Service1.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService1,
        }
    }
}
