//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDFCERGO.PIP.Adapters.FileNet
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfBase64Binary", Namespace="http://tempuri.org/", ItemName="base64Binary")]
    public class ArrayOfBase64Binary : System.Collections.Generic.List<byte[]>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentProperty", Namespace="http://tempuri.org/")]
    public partial class DocumentProperty : object
    {
        
        private HDFCERGO.PIP.Adapters.FileNet.ArrayOfString FileNameField;
        
        private HDFCERGO.PIP.Adapters.FileNet.ArrayOfString MIMETypeField;
        
        private HDFCERGO.PIP.Adapters.FileNet.ArrayOfBase64Binary FilesContentField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public HDFCERGO.PIP.Adapters.FileNet.ArrayOfString FileName
        {
            get
            {
                return this.FileNameField;
            }
            set
            {
                this.FileNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public HDFCERGO.PIP.Adapters.FileNet.ArrayOfString MIMEType
        {
            get
            {
                return this.MIMETypeField;
            }
            set
            {
                this.MIMETypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public HDFCERGO.PIP.Adapters.FileNet.ArrayOfBase64Binary FilesContent
        {
            get
            {
                return this.FilesContentField;
            }
            set
            {
                this.FilesContentField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HDFCERGO.PIP.Adapters.FileNet.ServiceSoap")]
    public interface ServiceSoap
    {
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddDocument", ReplyAction="*")]
        HDFCERGO.PIP.Adapters.FileNet.AddDocumentResponse AddDocument(HDFCERGO.PIP.Adapters.FileNet.AddDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddDocument", ReplyAction="*")]
        System.Threading.Tasks.Task<HDFCERGO.PIP.Adapters.FileNet.AddDocumentResponse> AddDocumentAsync(HDFCERGO.PIP.Adapters.FileNet.AddDocumentRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllDocumentList", ReplyAction="*")]
        HDFCERGO.PIP.Adapters.FileNet.getAllDocumentListResponse getAllDocumentList(HDFCERGO.PIP.Adapters.FileNet.getAllDocumentListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllDocumentList", ReplyAction="*")]
        System.Threading.Tasks.Task<HDFCERGO.PIP.Adapters.FileNet.getAllDocumentListResponse> getAllDocumentListAsync(HDFCERGO.PIP.Adapters.FileNet.getAllDocumentListRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDocumentContent", ReplyAction="*")]
        HDFCERGO.PIP.Adapters.FileNet.getDocumentContentResponse getDocumentContent(HDFCERGO.PIP.Adapters.FileNet.getDocumentContentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDocumentContent", ReplyAction="*")]
        System.Threading.Tasks.Task<HDFCERGO.PIP.Adapters.FileNet.getDocumentContentResponse> getDocumentContentAsync(HDFCERGO.PIP.Adapters.FileNet.getDocumentContentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDocumentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDocument", Namespace="http://tempuri.org/", Order=0)]
        public HDFCERGO.PIP.Adapters.FileNet.AddDocumentRequestBody Body;
        
        public AddDocumentRequest()
        {
        }
        
        public AddDocumentRequest(HDFCERGO.PIP.Adapters.FileNet.AddDocumentRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddDocumentRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string documentClass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public HDFCERGO.PIP.Adapters.FileNet.ArrayOfString fileNames;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public HDFCERGO.PIP.Adapters.FileNet.ArrayOfBase64Binary byteArray;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public HDFCERGO.PIP.Adapters.FileNet.ArrayOfString documentPropertyNames;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public HDFCERGO.PIP.Adapters.FileNet.ArrayOfString documentPropertyValues;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public HDFCERGO.PIP.Adapters.FileNet.ArrayOfString menuPropertyNames;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public HDFCERGO.PIP.Adapters.FileNet.ArrayOfString menuPropertyValues;
        
        public AddDocumentRequestBody()
        {
        }
        
        public AddDocumentRequestBody(string username, string password, string documentClass, HDFCERGO.PIP.Adapters.FileNet.ArrayOfString fileNames, HDFCERGO.PIP.Adapters.FileNet.ArrayOfBase64Binary byteArray, HDFCERGO.PIP.Adapters.FileNet.ArrayOfString documentPropertyNames, HDFCERGO.PIP.Adapters.FileNet.ArrayOfString documentPropertyValues, HDFCERGO.PIP.Adapters.FileNet.ArrayOfString menuPropertyNames, HDFCERGO.PIP.Adapters.FileNet.ArrayOfString menuPropertyValues)
        {
            this.username = username;
            this.password = password;
            this.documentClass = documentClass;
            this.fileNames = fileNames;
            this.byteArray = byteArray;
            this.documentPropertyNames = documentPropertyNames;
            this.documentPropertyValues = documentPropertyValues;
            this.menuPropertyNames = menuPropertyNames;
            this.menuPropertyValues = menuPropertyValues;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDocumentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDocumentResponse", Namespace="http://tempuri.org/", Order=0)]
        public HDFCERGO.PIP.Adapters.FileNet.AddDocumentResponseBody Body;
        
        public AddDocumentResponse()
        {
        }
        
        public AddDocumentResponse(HDFCERGO.PIP.Adapters.FileNet.AddDocumentResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddDocumentResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddDocumentResult;
        
        public AddDocumentResponseBody()
        {
        }
        
        public AddDocumentResponseBody(string AddDocumentResult)
        {
            this.AddDocumentResult = AddDocumentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllDocumentListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllDocumentList", Namespace="http://tempuri.org/", Order=0)]
        public HDFCERGO.PIP.Adapters.FileNet.getAllDocumentListRequestBody Body;
        
        public getAllDocumentListRequest()
        {
        }
        
        public getAllDocumentListRequest(HDFCERGO.PIP.Adapters.FileNet.getAllDocumentListRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAllDocumentListRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public HDFCERGO.PIP.Adapters.FileNet.ArrayOfString conditionalParameterNames;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public HDFCERGO.PIP.Adapters.FileNet.ArrayOfString conditionalParameterValues;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int maxRow;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string docType;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool searchAllRecords;
        
        public getAllDocumentListRequestBody()
        {
        }
        
        public getAllDocumentListRequestBody(string username, string password, HDFCERGO.PIP.Adapters.FileNet.ArrayOfString conditionalParameterNames, HDFCERGO.PIP.Adapters.FileNet.ArrayOfString conditionalParameterValues, int maxRow, string docType, bool searchAllRecords)
        {
            this.username = username;
            this.password = password;
            this.conditionalParameterNames = conditionalParameterNames;
            this.conditionalParameterValues = conditionalParameterValues;
            this.maxRow = maxRow;
            this.docType = docType;
            this.searchAllRecords = searchAllRecords;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllDocumentListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllDocumentListResponse", Namespace="http://tempuri.org/", Order=0)]
        public HDFCERGO.PIP.Adapters.FileNet.getAllDocumentListResponseBody Body;
        
        public getAllDocumentListResponse()
        {
        }
        
        public getAllDocumentListResponse(HDFCERGO.PIP.Adapters.FileNet.getAllDocumentListResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAllDocumentListResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getAllDocumentListResult;
        
        public getAllDocumentListResponseBody()
        {
        }
        
        public getAllDocumentListResponseBody(string getAllDocumentListResult)
        {
            this.getAllDocumentListResult = getAllDocumentListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDocumentContentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDocumentContent", Namespace="http://tempuri.org/", Order=0)]
        public HDFCERGO.PIP.Adapters.FileNet.getDocumentContentRequestBody Body;
        
        public getDocumentContentRequest()
        {
        }
        
        public getDocumentContentRequest(HDFCERGO.PIP.Adapters.FileNet.getDocumentContentRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getDocumentContentRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string documentId;
        
        public getDocumentContentRequestBody()
        {
        }
        
        public getDocumentContentRequestBody(string username, string password, string documentId)
        {
            this.username = username;
            this.password = password;
            this.documentId = documentId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDocumentContentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDocumentContentResponse", Namespace="http://tempuri.org/", Order=0)]
        public HDFCERGO.PIP.Adapters.FileNet.getDocumentContentResponseBody Body;
        
        public getDocumentContentResponse()
        {
        }
        
        public getDocumentContentResponse(HDFCERGO.PIP.Adapters.FileNet.getDocumentContentResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getDocumentContentResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HDFCERGO.PIP.Adapters.FileNet.DocumentProperty getDocumentContentResult;
        
        public getDocumentContentResponseBody()
        {
        }
        
        public getDocumentContentResponseBody(HDFCERGO.PIP.Adapters.FileNet.DocumentProperty getDocumentContentResult)
        {
            this.getDocumentContentResult = getDocumentContentResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface ServiceSoapChannel : HDFCERGO.PIP.Adapters.FileNet.ServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<HDFCERGO.PIP.Adapters.FileNet.ServiceSoap>, HDFCERGO.PIP.Adapters.FileNet.ServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), ServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HDFCERGO.PIP.Adapters.FileNet.AddDocumentResponse HDFCERGO.PIP.Adapters.FileNet.ServiceSoap.AddDocument(HDFCERGO.PIP.Adapters.FileNet.AddDocumentRequest request)
        {
            return base.Channel.AddDocument(request);
        }
        
        public string AddDocument(string username, string password, string documentClass, HDFCERGO.PIP.Adapters.FileNet.ArrayOfString fileNames, HDFCERGO.PIP.Adapters.FileNet.ArrayOfBase64Binary byteArray, HDFCERGO.PIP.Adapters.FileNet.ArrayOfString documentPropertyNames, HDFCERGO.PIP.Adapters.FileNet.ArrayOfString documentPropertyValues, HDFCERGO.PIP.Adapters.FileNet.ArrayOfString menuPropertyNames, HDFCERGO.PIP.Adapters.FileNet.ArrayOfString menuPropertyValues)
        {
            HDFCERGO.PIP.Adapters.FileNet.AddDocumentRequest inValue = new HDFCERGO.PIP.Adapters.FileNet.AddDocumentRequest();
            inValue.Body = new HDFCERGO.PIP.Adapters.FileNet.AddDocumentRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.documentClass = documentClass;
            inValue.Body.fileNames = fileNames;
            inValue.Body.byteArray = byteArray;
            inValue.Body.documentPropertyNames = documentPropertyNames;
            inValue.Body.documentPropertyValues = documentPropertyValues;
            inValue.Body.menuPropertyNames = menuPropertyNames;
            inValue.Body.menuPropertyValues = menuPropertyValues;
            HDFCERGO.PIP.Adapters.FileNet.AddDocumentResponse retVal = ((HDFCERGO.PIP.Adapters.FileNet.ServiceSoap)(this)).AddDocument(inValue);
            return retVal.Body.AddDocumentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HDFCERGO.PIP.Adapters.FileNet.AddDocumentResponse> HDFCERGO.PIP.Adapters.FileNet.ServiceSoap.AddDocumentAsync(HDFCERGO.PIP.Adapters.FileNet.AddDocumentRequest request)
        {
            return base.Channel.AddDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<HDFCERGO.PIP.Adapters.FileNet.AddDocumentResponse> AddDocumentAsync(string username, string password, string documentClass, HDFCERGO.PIP.Adapters.FileNet.ArrayOfString fileNames, HDFCERGO.PIP.Adapters.FileNet.ArrayOfBase64Binary byteArray, HDFCERGO.PIP.Adapters.FileNet.ArrayOfString documentPropertyNames, HDFCERGO.PIP.Adapters.FileNet.ArrayOfString documentPropertyValues, HDFCERGO.PIP.Adapters.FileNet.ArrayOfString menuPropertyNames, HDFCERGO.PIP.Adapters.FileNet.ArrayOfString menuPropertyValues)
        {
            HDFCERGO.PIP.Adapters.FileNet.AddDocumentRequest inValue = new HDFCERGO.PIP.Adapters.FileNet.AddDocumentRequest();
            inValue.Body = new HDFCERGO.PIP.Adapters.FileNet.AddDocumentRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.documentClass = documentClass;
            inValue.Body.fileNames = fileNames;
            inValue.Body.byteArray = byteArray;
            inValue.Body.documentPropertyNames = documentPropertyNames;
            inValue.Body.documentPropertyValues = documentPropertyValues;
            inValue.Body.menuPropertyNames = menuPropertyNames;
            inValue.Body.menuPropertyValues = menuPropertyValues;
            return ((HDFCERGO.PIP.Adapters.FileNet.ServiceSoap)(this)).AddDocumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HDFCERGO.PIP.Adapters.FileNet.getAllDocumentListResponse HDFCERGO.PIP.Adapters.FileNet.ServiceSoap.getAllDocumentList(HDFCERGO.PIP.Adapters.FileNet.getAllDocumentListRequest request)
        {
            return base.Channel.getAllDocumentList(request);
        }
        
        public string getAllDocumentList(string username, string password, HDFCERGO.PIP.Adapters.FileNet.ArrayOfString conditionalParameterNames, HDFCERGO.PIP.Adapters.FileNet.ArrayOfString conditionalParameterValues, int maxRow, string docType, bool searchAllRecords)
        {
            HDFCERGO.PIP.Adapters.FileNet.getAllDocumentListRequest inValue = new HDFCERGO.PIP.Adapters.FileNet.getAllDocumentListRequest();
            inValue.Body = new HDFCERGO.PIP.Adapters.FileNet.getAllDocumentListRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.conditionalParameterNames = conditionalParameterNames;
            inValue.Body.conditionalParameterValues = conditionalParameterValues;
            inValue.Body.maxRow = maxRow;
            inValue.Body.docType = docType;
            inValue.Body.searchAllRecords = searchAllRecords;
            HDFCERGO.PIP.Adapters.FileNet.getAllDocumentListResponse retVal = ((HDFCERGO.PIP.Adapters.FileNet.ServiceSoap)(this)).getAllDocumentList(inValue);
            return retVal.Body.getAllDocumentListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HDFCERGO.PIP.Adapters.FileNet.getAllDocumentListResponse> HDFCERGO.PIP.Adapters.FileNet.ServiceSoap.getAllDocumentListAsync(HDFCERGO.PIP.Adapters.FileNet.getAllDocumentListRequest request)
        {
            return base.Channel.getAllDocumentListAsync(request);
        }
        
        public System.Threading.Tasks.Task<HDFCERGO.PIP.Adapters.FileNet.getAllDocumentListResponse> getAllDocumentListAsync(string username, string password, HDFCERGO.PIP.Adapters.FileNet.ArrayOfString conditionalParameterNames, HDFCERGO.PIP.Adapters.FileNet.ArrayOfString conditionalParameterValues, int maxRow, string docType, bool searchAllRecords)
        {
            HDFCERGO.PIP.Adapters.FileNet.getAllDocumentListRequest inValue = new HDFCERGO.PIP.Adapters.FileNet.getAllDocumentListRequest();
            inValue.Body = new HDFCERGO.PIP.Adapters.FileNet.getAllDocumentListRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.conditionalParameterNames = conditionalParameterNames;
            inValue.Body.conditionalParameterValues = conditionalParameterValues;
            inValue.Body.maxRow = maxRow;
            inValue.Body.docType = docType;
            inValue.Body.searchAllRecords = searchAllRecords;
            return ((HDFCERGO.PIP.Adapters.FileNet.ServiceSoap)(this)).getAllDocumentListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HDFCERGO.PIP.Adapters.FileNet.getDocumentContentResponse HDFCERGO.PIP.Adapters.FileNet.ServiceSoap.getDocumentContent(HDFCERGO.PIP.Adapters.FileNet.getDocumentContentRequest request)
        {
            return base.Channel.getDocumentContent(request);
        }
        
        public HDFCERGO.PIP.Adapters.FileNet.DocumentProperty getDocumentContent(string username, string password, string documentId)
        {
            HDFCERGO.PIP.Adapters.FileNet.getDocumentContentRequest inValue = new HDFCERGO.PIP.Adapters.FileNet.getDocumentContentRequest();
            inValue.Body = new HDFCERGO.PIP.Adapters.FileNet.getDocumentContentRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.documentId = documentId;
            HDFCERGO.PIP.Adapters.FileNet.getDocumentContentResponse retVal = ((HDFCERGO.PIP.Adapters.FileNet.ServiceSoap)(this)).getDocumentContent(inValue);
            return retVal.Body.getDocumentContentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HDFCERGO.PIP.Adapters.FileNet.getDocumentContentResponse> HDFCERGO.PIP.Adapters.FileNet.ServiceSoap.getDocumentContentAsync(HDFCERGO.PIP.Adapters.FileNet.getDocumentContentRequest request)
        {
            return base.Channel.getDocumentContentAsync(request);
        }
        
        public System.Threading.Tasks.Task<HDFCERGO.PIP.Adapters.FileNet.getDocumentContentResponse> getDocumentContentAsync(string username, string password, string documentId)
        {
            HDFCERGO.PIP.Adapters.FileNet.getDocumentContentRequest inValue = new HDFCERGO.PIP.Adapters.FileNet.getDocumentContentRequest();
            inValue.Body = new HDFCERGO.PIP.Adapters.FileNet.getDocumentContentRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.documentId = documentId;
            return ((HDFCERGO.PIP.Adapters.FileNet.ServiceSoap)(this)).getDocumentContentAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://202.191.196.210/RefundManagementWebservice/service.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://202.191.196.210/RefundManagementWebservice/service.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ServiceSoap,
            
            ServiceSoap12,
        }
    }
}
