//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDFCERGO.PIP.Adapters.EKYCService.EKYCPie
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HDFCERGO.PIP.Adapters.EKYCService.EKYCPie.IEKYCService")]
    public interface IEKYCService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEKYCService/DoWork", ReplyAction="http://tempuri.org/IEKYCService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEKYCService/DoWork", ReplyAction="http://tempuri.org/IEKYCService/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEKYCService/ValidateAadharNo", ReplyAction="http://tempuri.org/IEKYCService/ValidateAadharNoResponse")]
        string ValidateAadharNo(string aadharReqXMLStr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEKYCService/ValidateAadharNo", ReplyAction="http://tempuri.org/IEKYCService/ValidateAadharNoResponse")]
        System.Threading.Tasks.Task<string> ValidateAadharNoAsync(string aadharReqXMLStr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEKYCService/GetAadharCardDetails", ReplyAction="http://tempuri.org/IEKYCService/GetAadharCardDetailsResponse")]
        string GetAadharCardDetails(string aadharReqXMLStr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEKYCService/GetAadharCardDetails", ReplyAction="http://tempuri.org/IEKYCService/GetAadharCardDetailsResponse")]
        System.Threading.Tasks.Task<string> GetAadharCardDetailsAsync(string aadharReqXMLStr);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IEKYCServiceChannel : HDFCERGO.PIP.Adapters.EKYCService.EKYCPie.IEKYCService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class EKYCServiceClient : System.ServiceModel.ClientBase<HDFCERGO.PIP.Adapters.EKYCService.EKYCPie.IEKYCService>, HDFCERGO.PIP.Adapters.EKYCService.EKYCPie.IEKYCService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public EKYCServiceClient() : 
                base(EKYCServiceClient.GetDefaultBinding(), EKYCServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IEKYCService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EKYCServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(EKYCServiceClient.GetBindingForEndpoint(endpointConfiguration), EKYCServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EKYCServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(EKYCServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EKYCServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(EKYCServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EKYCServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public void DoWork()
        {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync()
        {
            return base.Channel.DoWorkAsync();
        }
        
        public string ValidateAadharNo(string aadharReqXMLStr)
        {
            return base.Channel.ValidateAadharNo(aadharReqXMLStr);
        }
        
        public System.Threading.Tasks.Task<string> ValidateAadharNoAsync(string aadharReqXMLStr)
        {
            return base.Channel.ValidateAadharNoAsync(aadharReqXMLStr);
        }
        
        public string GetAadharCardDetails(string aadharReqXMLStr)
        {
            return base.Channel.GetAadharCardDetails(aadharReqXMLStr);
        }
        
        public System.Threading.Tasks.Task<string> GetAadharCardDetailsAsync(string aadharReqXMLStr)
        {
            return base.Channel.GetAadharCardDetailsAsync(aadharReqXMLStr);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IEKYCService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IEKYCService))
            {
                return new System.ServiceModel.EndpointAddress("http://202.191.196.210/UAT/OnlineProducts/EkycPie/EKYCService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return EKYCServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IEKYCService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return EKYCServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IEKYCService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IEKYCService,
        }
    }
}
